import { ValidatedForm } from "@carbon/form";
import {
  Button,
  Combobox as ComboboxBase,
  Heading,
  HStack,
  IconButton,
  Input as InputBase,
  ModalDrawer,
  ModalDrawerBody,
  ModalDrawerContent,
  ModalDrawerFooter,
  ModalDrawerHeader,
  ModalDrawerProvider,
  ModalDrawerTitle,
  NumberField,
  NumberInput,
  Switch,
  toast,
  VStack
} from "@carbon/react";
import { Trans, useLingui } from "@lingui/react/macro";
import type { PostgrestResponse } from "@supabase/supabase-js";
import { useCallback, useEffect, useMemo, useState } from "react";
import { LuPlus, LuTrash } from "react-icons/lu";
import { useFetcher } from "react-router";
import type { z } from "zod";
import {
  AccountControlled,
  CustomFormFields,
  Hidden,
  Input,
  Select,
  Submit,
  TextArea
} from "~/components/Form";
import Country from "~/components/Form/Country";
import { usePermissions } from "~/hooks";
import { path } from "~/utils/path";
import {
  taxCalculationTypes,
  taxCodeValidator,
  taxReportingCategories
} from "../../accounting.models";
import type { EffectiveTaxComponent } from "../../accounting.utils";
import {
  computeEffectiveTaxPercent,
  filterEffectiveComponents
} from "../../accounting.utils";

/**
 * A component row while it is being edited. Structurally identical to
 * `EffectiveTaxComponent` so the rows can be fed straight into
 * `filterEffectiveComponents` / `computeEffectiveTaxPercent` for the preview,
 * and JSON-serialized straight into the `components` hidden field (where the
 * route action re-validates them with `taxCodeComponentValidator`).
 *
 * `rate` is ALWAYS a fraction (0..1) here — same units as the database CHECK
 * and the validator. The UI shows/accepts percents and converts on the edges
 * via `rateToPercent` / `percentToRate`.
 */
type ComponentRow = EffectiveTaxComponent;

/**
 * Client-side row id for a not-yet-persisted component. `upsertTaxCode`
 * reconciles by id against the ids already in the database, so an id it has
 * never seen is treated as an insert (and the real id is generated by Postgres).
 */
function newRowId() {
  return `new-${Math.random().toString(36).substring(2, 9)}`;
}

/** Fraction (0.09975) → percent (9.975), without binary-float noise. */
function rateToPercent(rate: number) {
  return Math.round(rate * 1e10) / 1e8;
}

/** Percent (9.975) → fraction (0.09975), without binary-float noise. */
function percentToRate(percent: number) {
  return Math.round(percent * 1e8) / 1e10;
}

/** Fraction (0.14975) → "14.975%". Locale-free so SSR and client agree. */
function formatPercent(fraction: number) {
  return `${Math.round(fraction * 1e10) / 1e8}%`;
}

function emptyComponentRow(sequence: number): ComponentRow {
  return {
    id: newRowId(),
    name: "",
    taxAuthorityId: null,
    rate: 0,
    sequence,
    isCompound: false,
    isRecoverable: false,
    salesTaxAccountId: null,
    purchaseTaxAccountId: null,
    effectiveDate: null,
    expirationDate: null
  };
}

function parseComponentRows(serialized: string | undefined): ComponentRow[] {
  if (!serialized) return [emptyComponentRow(1)];
  let parsed: unknown;
  try {
    parsed = JSON.parse(serialized);
  } catch {
    return [emptyComponentRow(1)];
  }
  if (!Array.isArray(parsed) || parsed.length === 0) {
    return [emptyComponentRow(1)];
  }
  return parsed.map((raw, index) => {
    const row = (raw ?? {}) as Partial<ComponentRow>;
    return {
      id: row.id ?? newRowId(),
      name: row.name ?? "",
      taxAuthorityId: row.taxAuthorityId ?? null,
      rate: typeof row.rate === "number" ? row.rate : Number(row.rate ?? 0),
      sequence: typeof row.sequence === "number" ? row.sequence : index + 1,
      isCompound: row.isCompound === true,
      isRecoverable: row.isRecoverable === true,
      salesTaxAccountId: row.salesTaxAccountId ?? null,
      purchaseTaxAccountId: row.purchaseTaxAccountId ?? null,
      effectiveDate: row.effectiveDate ?? null,
      expirationDate: row.expirationDate ?? null
    };
  });
}

type TaxCodeComponentRowProps = {
  row: ComponentRow;
  index: number;
  canRemove: boolean;
  isDisabled: boolean;
  taxAuthorityOptions: { value: string; label: string }[];
  onChange: (index: number, patch: Partial<ComponentRow>) => void;
  onRemove: (index: number) => void;
};

const TaxCodeComponentRow = ({
  row,
  index,
  canRemove,
  isDisabled,
  taxAuthorityOptions,
  onChange,
  onRemove
}: TaxCodeComponentRowProps) => {
  const { t } = useLingui();

  return (
    <div className="flex flex-col gap-2 rounded-lg border border-border p-3">
      <div className="grid grid-cols-1 sm:grid-cols-[minmax(0,1.4fr)_minmax(0,1.2fr)_110px_90px_40px] gap-2 items-start">
        <InputBase
          aria-label={t`Component Name`}
          placeholder={t`Component name, e.g. GST`}
          value={row.name}
          onChange={(e) => onChange(index, { name: e.target.value })}
          isDisabled={isDisabled}
          size="sm"
        />
        <ComboboxBase
          aria-label={t`Tax Authority`}
          options={taxAuthorityOptions}
          value={row.taxAuthorityId ?? ""}
          onChange={(value) =>
            onChange(index, { taxAuthorityId: value || null })
          }
          placeholder={t`Tax authority`}
          isReadOnly={isDisabled}
          size="sm"
        />
        {/* Rate is entered as a PERCENT and stored as a FRACTION (0..1). */}
        <NumberField
          aria-label={t`Rate (%)`}
          value={rateToPercent(row.rate)}
          onChange={(value) =>
            onChange(index, {
              rate: percentToRate(Number.isNaN(value) ? 0 : value)
            })
          }
          formatOptions={{ maximumFractionDigits: 4 }}
          minValue={0}
          maxValue={100}
          isDisabled={isDisabled}
        >
          <NumberInput
            className="text-right font-mono tabular-nums"
            size="sm"
          />
        </NumberField>
        <NumberField
          aria-label={t`Sequence`}
          value={row.sequence}
          onChange={(value) =>
            onChange(index, {
              sequence: Number.isNaN(value) ? index + 1 : Math.trunc(value)
            })
          }
          formatOptions={{ maximumFractionDigits: 0 }}
          minValue={1}
          isDisabled={isDisabled}
        >
          <NumberInput
            className="text-right font-mono tabular-nums"
            size="sm"
          />
        </NumberField>
        <IconButton
          aria-label={t`Remove component`}
          icon={<LuTrash />}
          isDisabled={isDisabled || !canRemove}
          onClick={() => onRemove(index)}
          size="sm"
          variant="ghost"
        />
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
        <AccountControlled
          value={row.salesTaxAccountId ?? ""}
          onChange={(value) =>
            onChange(index, { salesTaxAccountId: value || null })
          }
          placeholder={t`Sales tax account`}
          isReadOnly={isDisabled}
          size="sm"
        />
        <AccountControlled
          value={row.purchaseTaxAccountId ?? ""}
          onChange={(value) =>
            onChange(index, { purchaseTaxAccountId: value || null })
          }
          placeholder={t`Purchase tax account`}
          isReadOnly={isDisabled}
          size="sm"
        />
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
        <InputBase
          aria-label={t`Effective Date`}
          type="date"
          value={row.effectiveDate ?? ""}
          onChange={(e) =>
            onChange(index, { effectiveDate: e.target.value || null })
          }
          isDisabled={isDisabled}
          size="sm"
        />
        <InputBase
          aria-label={t`Expiration Date`}
          type="date"
          value={row.expirationDate ?? ""}
          onChange={(e) =>
            onChange(index, { expirationDate: e.target.value || null })
          }
          isDisabled={isDisabled}
          size="sm"
        />
      </div>

      <HStack spacing={4}>
        <Switch
          checked={row.isCompound}
          onCheckedChange={(checked) =>
            onChange(index, { isCompound: checked })
          }
          disabled={isDisabled}
          label={t`Compound`}
          variant="small"
        />
        <Switch
          checked={row.isRecoverable}
          onCheckedChange={(checked) =>
            onChange(index, { isRecoverable: checked })
          }
          disabled={isDisabled}
          label={t`Recoverable`}
          variant="small"
        />
      </HStack>
    </div>
  );
};

type TaxCodeFormProps = {
  /** `components` carries the child rows as a JSON string (see the validator). */
  initialValues: z.infer<typeof taxCodeValidator>;
  /** Options for the per-component authority select. Fed by the route loader. */
  taxAuthorities?: { id: string; name: string }[];
  type?: "modal" | "drawer";
  open?: boolean;
  onClose: (data?: { id: string; name: string }) => void;
};

const TaxCodeForm = ({
  initialValues,
  taxAuthorities = [],
  open = true,
  type = "drawer",
  onClose
}: TaxCodeFormProps) => {
  const { t } = useLingui();
  const permissions = usePermissions();
  const fetcher = useFetcher<PostgrestResponse<{ id: string }>>();

  const [rows, setRows] = useState<ComponentRow[]>(() =>
    parseComponentRows(initialValues.components)
  );

  useEffect(() => {
    if (type !== "modal") return;

    if (fetcher.state === "loading" && fetcher.data?.data) {
      onClose?.();
      toast.success(t`Created tax code`);
    } else if (fetcher.state === "idle" && fetcher.data?.error) {
      toast.error(t`Failed to create tax code: ${fetcher.data.error.message}`);
    }
  }, [fetcher.data, fetcher.state, onClose, type, t]);

  const isEditing = initialValues.id !== undefined;
  const isDisabled = isEditing
    ? !permissions.can("update", "accounting")
    : !permissions.can("create", "accounting");

  const calculationTypeOptions = taxCalculationTypes.map((v) => ({
    label: v,
    value: v
  }));
  const reportingCategoryOptions = taxReportingCategories.map((v) => ({
    label: v,
    value: v
  }));
  const taxAuthorityOptions = useMemo(
    () =>
      taxAuthorities.map((authority) => ({
        value: authority.id,
        label: authority.name
      })),
    [taxAuthorities]
  );

  const handleChange = useCallback(
    (index: number, patch: Partial<ComponentRow>) => {
      setRows((prev) =>
        prev.map((row, i) => (i === index ? { ...row, ...patch } : row))
      );
    },
    []
  );

  const handleRemove = useCallback((index: number) => {
    setRows((prev) =>
      prev.length > 1 ? prev.filter((_, i) => i !== index) : prev
    );
  }, []);

  const handleAdd = useCallback(() => {
    setRows((prev) => [
      ...prev,
      emptyComponentRow(
        prev.reduce((max, row) => Math.max(max, row.sequence), 0) + 1
      )
    ]);
  }, []);

  const today = useMemo(() => new Date().toISOString().slice(0, 10), []);
  const effectiveRate = useMemo(
    () => computeEffectiveTaxPercent(1, filterEffectiveComponents(rows, today)),
    [rows, today]
  );

  return (
    <ModalDrawerProvider type={type}>
      <ModalDrawer
        open={open}
        onOpenChange={(open) => {
          if (!open) onClose?.();
        }}
      >
        <ModalDrawerContent size="lg">
          <ValidatedForm
            validator={taxCodeValidator}
            method="post"
            action={
              isEditing
                ? path.to.taxCode(initialValues.id!)
                : path.to.newTaxCode
            }
            defaultValues={initialValues}
            fetcher={fetcher}
            className="flex flex-col h-full"
          >
            <ModalDrawerHeader>
              <ModalDrawerTitle>
                {isEditing ? (
                  <Trans>Edit Tax Code</Trans>
                ) : (
                  <Trans>New Tax Code</Trans>
                )}
              </ModalDrawerTitle>
            </ModalDrawerHeader>
            <ModalDrawerBody>
              <Hidden name="id" />
              <Hidden name="type" value={type} />
              {/* The whole component array travels as one JSON field. */}
              <Hidden name="components" value={JSON.stringify(rows)} />
              <VStack spacing={4}>
                <Input name="name" label={t`Name`} />
                <Input name="description" label={t`Description`} />
                <Select
                  name="calculationType"
                  label={t`Calculation Type`}
                  options={calculationTypeOptions}
                  helperText={t`Reverse Charge shifts the tax to the buyer instead of charging it`}
                />
                <Select
                  name="reportingCategory"
                  label={t`Reporting Category`}
                  options={reportingCategoryOptions}
                  helperText={t`How this treatment is grouped on tax returns`}
                />
                <TextArea
                  name="invoiceMessage"
                  label={t`Invoice Message`}
                  placeholder={t`Printed on documents that use this tax code`}
                />
                <Country
                  name="countryCode"
                  label={t`Address Match — Country`}
                  helperText={t`Suggestion only. Used to suggest this code for matching addresses; it never determines the tax on a document.`}
                />
                <Input
                  name="state"
                  label={t`Address Match — State / Province`}
                  helperText={t`Suggestion only. Leave blank to match every state in the country above.`}
                />

                <VStack spacing={2}>
                  <div className="flex items-center justify-between w-full gap-3 flex-wrap">
                    <Heading size="h4">
                      <Trans>Components</Trans>
                    </Heading>
                    <Button
                      variant="secondary"
                      size="sm"
                      leftIcon={<LuPlus />}
                      isDisabled={isDisabled}
                      onClick={handleAdd}
                    >
                      <Trans>Add Component</Trans>
                    </Button>
                  </div>

                  <div className="flex flex-col gap-2 w-full">
                    {rows.map((row, index) => (
                      <TaxCodeComponentRow
                        key={row.id}
                        row={row}
                        index={index}
                        canRemove={rows.length > 1}
                        isDisabled={isDisabled}
                        taxAuthorityOptions={taxAuthorityOptions}
                        onChange={handleChange}
                        onRemove={handleRemove}
                      />
                    ))}
                  </div>

                  <p className="text-sm text-muted-foreground tabular-nums">
                    <Trans>
                      Effective rate today: {formatPercent(effectiveRate)}
                    </Trans>
                  </p>
                </VStack>

                <CustomFormFields table="taxCode" />
              </VStack>
            </ModalDrawerBody>
            <ModalDrawerFooter>
              <HStack>
                <Submit isDisabled={isDisabled}>
                  <Trans>Save</Trans>
                </Submit>
              </HStack>
            </ModalDrawerFooter>
          </ValidatedForm>
        </ModalDrawerContent>
      </ModalDrawer>
    </ModalDrawerProvider>
  );
};

export default TaxCodeForm;
